# Generated by Django 5.2.13 on 2026-04-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "journey"), name="unique_ticket_seat_journey"
            ),
        ),
    ]
