# Generated by Django 5.2.13 on 2026-04-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0002_ticket_unique_ticket_seat_journey"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.CheckConstraint(
                condition=models.Q(("arrival_time__gt", models.F("departure_time"))),
                name="arrival_time_after_departure_time",
            ),
        ),
    ]
