# Generated by Django 5.2.13 on 2026-04-17 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0003_journey_arrival_time_after_departure_time"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_journey",
        ),
        migrations.AddConstraint(
            model_name="route",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("destination")), _negated=True),
                name="source_not_equal_destination",
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("seat", "journey", "cargo"), name="unique_ticket_seat_journey"
            ),
        ),
    ]
