# Generated by Django 5.2.13 on 2026-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("station_api", "0004_remove_ticket_unique_ticket_seat_journey_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-created_at",)},
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="cargo",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="seat",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="cargo_num",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="train",
            name="places_in_cargo",
            field=models.PositiveIntegerField(),
        ),
    ]
