# Generated by Django 5.2.13 on 2026-04-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
